import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../style/globals.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es_MX">
      <body className={inter.className}>{children}
        <footer>
          <a href="https://nextjs.org">Powered by Next.js</a>
        </footer>
      </body>
    </html>
  );
}
